/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-07 01:50:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Documents/Goc_Hoc_Tap/JAVAWEB/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/JWEB_ML201/WEB-INF/lib/jstl-1.2_1.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2_1.jar", Long.valueOf(1669661659049L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	font-family: 'Roboto', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".containerfulls {\r\n");
      out.write("	max-width: 100vw;\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sibar_container {\r\n");
      out.write("	width: 20vw;\r\n");
      out.write("	background-color: blue;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".right_container {\r\n");
      out.write("	width: 80vw;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo_t {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	border-bottom: 1px solid white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("	color: azure;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sibar_item {\r\n");
      out.write("	padding: 20px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sibar_item li {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	padding: 13px 20px;\r\n");
      out.write("	border-radius: 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sibar_item li:hover {\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sibar_item li span {\r\n");
      out.write("	border: 1px solid white;\r\n");
      out.write("	width: 30px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	line-height: 30px;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sibar_item li a {\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: azure;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* right */\r\n");
      out.write(".top_menu_item {\r\n");
      out.write("	box-shadow: rgba(0, 0, 0, 0.02) 0px 1px 3px 0px, rgba(27, 31, 35, 0.15)\r\n");
      out.write("		0px 0px 0px 1px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	background-color: aliceblue;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("	margin-left: 20px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	color: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*  */\r\n");
      out.write(".menu_itemRight {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	padding-right: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu_itemRight li {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	border: 2px solid blue;\r\n");
      out.write("	border-radius: 7px;\r\n");
      out.write("	padding: 4px 12px;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu_itemRight li a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".right_container_bt {\r\n");
      out.write("	height: calc(100vh - 50px);\r\n");
      out.write("	background-color: #d7d7d7;\r\n");
      out.write("	padding: 20px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title_dm {\r\n");
      out.write("	color: gray;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	padding: 10px 10px;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	box-shadow: rgba(0, 0, 0, 0.02) 0px 1px 3px 0px, rgba(27, 31, 35, 0.15)\r\n");
      out.write("		0px 0px 0px 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item_data {\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item_data h6 {\r\n");
      out.write("	margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item_data_text {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin-right: 30px;\r\n");
      out.write("	padding: 7px 15px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	color: blue;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit_button {\r\n");
      out.write("	margin-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit_button button {\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("	padding: 6px 15px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".create {\r\n");
      out.write("	border: 1px solid blue;\r\n");
      out.write("	color: blue;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cancel {\r\n");
      out.write("	border: 1px solid red;\r\n");
      out.write("	color: red;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* phòng ban */\r\n");
      out.write(".right_container_bt {\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container_data {\r\n");
      out.write("	width: 60%;\r\n");
      out.write("	height: 70%;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	margin-right: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".data {\r\n");
      out.write("	padding: 20px 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container_user {\r\n");
      out.write("	width: 40%;\r\n");
      out.write("	height: 70%;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img_nen {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user_data {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".avatar {\r\n");
      out.write("	width: 80px;\r\n");
      out.write("	height: 80px;\r\n");
      out.write("	border: 2px solid green;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	margin-top: -40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user_data h5 {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user_data h3 {\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user_data p {\r\n");
      out.write("	font-size: 6px;\r\n");
      out.write("	padding-bottom: 20px;\r\n");
      out.write("	border-bottom: 2px solid gray;\r\n");
      out.write("	padding: 10px 10px\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"containerfulls\">\r\n");
      out.write("		<div class=\"sibar_container\">\r\n");
      out.write("			<div class=\"logo_t\">WEB HRM</div>\r\n");
      out.write("			<div class=\"sibar_item\">\r\n");
      out.write("				<li><span class=\"fa fa-home\"></span> <a href=\"/JWEB_ML201/home\">HOME</a></li>\r\n");
      out.write("				<li><span class=\"fa fa-user\"></span> <a href=\"\">USER\r\n");
      out.write("						PROFILE</a></li>\r\n");
      out.write("				<li><span class=\"fa fa-briefcase\"></span> <a\r\n");
      out.write("					href=\"/JWEB_ML201/ListDepartmentSevlet\">PHÒNG BAN</a></li>\r\n");
      out.write("				<li><span class=\"fa fa-address-card\"></span> <a\r\n");
      out.write("					href=\"/JWEB_ML201/ListEmployeeServlet\">NHÂN VIÊN</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"right_container\">\r\n");
      out.write("			<div class=\"top_menu_item\">\r\n");
      out.write("				<div class=\"title\">\r\n");
      out.write("					<span class=\"fa fa-tongle\"></span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"menu_itemRight\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"right_container_bt\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"container_data\">\r\n");
      out.write("					<form action=\"/JWEB_ML201/updateDepartment\" method=\"post\">\r\n");
      out.write("						<div class=\"data\">\r\n");
      out.write("							<h4> SỬA PHÒNG BAN</h4>\r\n");
      out.write("							<div class=\"item_data\">\r\n");
      out.write("								<h6>MÃ PHÒNG BAN</h6>\r\n");
      out.write("								<input type=\"text\" class=\"item_data_text\" name=\"department_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lis.department_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"item_data\">\r\n");
      out.write("								<h6>TÊN PHÒNG BAN</h6>\r\n");
      out.write("								<input type=\"text\" class=\"item_data_text\" name=\"department_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lis.department_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"item_data\">\r\n");
      out.write("								<h6>MÔ TẢ</h6>\r\n");
      out.write("								<input type=\"text\" class=\"item_data_text\" name=\"mota\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lis.mota }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"submit_button\">\r\n");
      out.write("								<button class=\"create\" type=\"submit\">CẬP NHẬT</button>\r\n");
      out.write("								<button class=\"cancel\">Cancel</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"container_user\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"https://thuthuatphanmem.vn/uploads/2018/04/10/hinh-nen-bong-hong-dep_052333650.jpg\"\r\n");
      out.write("						alt=\"\" class=\"img_nen\">\r\n");
      out.write("					<div class=\"user_data\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://img.thuthuattinhoc.vn/uploads/2019/01/08/anh-anime-boy-dep-nhat_101905549.jpg\"\r\n");
      out.write("							class=\"avatar\" alt=\"\">\r\n");
      out.write("						<h5>Lữ Hành</h5>\r\n");
      out.write("						<h3>CONG TY TNHH PHAN PHOI LU HANH</h3>\r\n");
      out.write("						<p>17-My an,Phuong Bac My Phu , Quan Ngu Hanh Son , TP Đà Nẵng\r\n");
      out.write("\r\n");
      out.write("						\r\n");
      out.write("						<p>\r\n");
      out.write("						<div>\r\n");
      out.write("							<i class=\"fa-brands fa-facebook\"></i> <span\r\n");
      out.write("								class=\"fa-brands fa-facebook\"></span> <span\r\n");
      out.write("								class=\"fa-brands fa-youtobe\"></span> <span\r\n");
      out.write("								class=\"fa-brands fa-home\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /view/Update.jsp(255,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li><a href=\"\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></li>\r\n");
          out.write("						<li><a href=\"/JWEB_ML201/LogoutServlet\">Logout</a></li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /view/Update.jsp(259,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li><a >Khách Hàng</a></li>\r\n");
          out.write("						<li><a href=\"/JWEB_ML201/login\">Login</a></li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
